[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "claude-scons-db"
version = "0.1.0"
description = "Experiment with using Claude to search for correlations within the Scons-DB database"
authors = [{ name = "Craig Lage" }]
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
requires-python = ">=3.13"
dependencies = [
    "numpy",
]

[project.optional-dependencies]
dev = ["black", "mypy", "pytest"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 110
target-version = ["py313"]
